apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: checkout-demo
  description: System that is responsible for the checkout-demo process.
  links:
    - url: https://github.com/nonexistingorg/nonexisting-repo1
      title: checkout-demo-api
      icon: github
    - url: https://github.com/nonexistingorg/nonexisting-repo2
      title: checkout-demo-web
      icon: github
    - url: https://github.com/nonexistingorg/nonexisting-repo3
      title: checkout-demo-mobile
      icon: github
spec:
  owner: daas
  repos:
    - checkout-demo-api
    - checkout-demo-web
    - checkout-demo-mobile

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: checkout-demo-api-openapi
  description: Provides API for checkout-demo Service
spec:
  type: openapi
  lifecycle: production
  owner: daas
  system: checkout-demo
  definition: "https://raw.githubusercontent.com/backstage/backstage/refs/heads/master/plugins/catalog-backend/src/schema/openapi.yaml"

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-demo-api
  description: checkout-demo web API.
spec:
  type: dotnet-web-api
  owner: daas
  lifecycle: production
  system: checkout-demo
  providesApis:
    - api:checkout-demo-api-openapi
  dependsOn:
    - resource:checkout-demo-database

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-demo-web
  description: React web application
spec:
  type: react-web-application
  owner: daas
  lifecycle: production
  system: checkout-demo
  consumesApis:
    - api:checkout-demo-api-openapi

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-demo-mobile
  description: React native mobile application
spec:
  type: react-native-mobile-application
  owner: daas
  lifecycle: production
  system: checkout-demo
  consumesApis:
    - api:checkout-demo-api-openapi

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: checkout-demo-database
  description: Database Access for checkout-demo Service
spec:
  type: mssql-database-access
  owner: database-team
  lifecycle: production
  system: checkout-demo
